#
# OCNE Deployment Tool
#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Ansible playbook to remove/delete an OCNE environment.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# yamllint disable

---

- name: Remove the Environment
  hosts: ocne_op
  gather_facts: false

  tasks:

  - name: Remove the environment
    command: olcnectl --api-server 127.0.0.1:8091 environment delete
             --environment-name {{ ocne_environment }}
    ignore_errors: yes
