#
# OCNE Deployment Tool
#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Ansible playbook to configure kubectl for the installed cluster.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# yamllint disable

---

- name: Set up kubectl on the Master Node
  hosts: ocne_kube_control
  gather_facts: false

  tasks:

  - name: Set up kubectl
    shell: |
            rm $HOME/.kube/config
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            echo 'export KUBECONFIG=$HOME/.kube/config' >> $HOME/.bashrc
