#
# OCNE Deployment Tool
#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# Description: Ansible playbook to uninstall
# OCNE Operator Lifecycle Manager and Helm modules.
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# yamllint disable

---

- name: Remove OLM and Helm from an OCNE environment
  hosts: ocne_op
  gather_facts: false

  tasks:

  - name: Remove OLM Module
    command: olcnectl module uninstall \
             --environment-name {{ ocne_environment }} \
             --name {{ ocne_olm }}
    ignore_errors: yes

  - name: Remove Helm Module
    command: olcnectl module uninstall \
             --environment-name {{ ocne_environment }} \
             --name {{ ocne_helm }}
    ignore_errors: yes
